// ========== NEWS DATABASE ==========
const newsDB = [
  {
    id: 1,
    title: 'OB54 Patch Notes — Full Breakdown',
    excerpt: 'Check out all the new features, balance changes and bug fixes coming in the OB54 update.',
    content: 'The OB54 update brings massive changes to Free Fire including a new weapon balance pass, improved anti-cheat systems, and a brand new ranked season. The update introduces the new "Fire Kickoff" football-themed campaign starting June 5. New character adjustments have been made to optimize gameplay balance. Also included are quality-of-life improvements to the UI and store interface.',
    category: 'update',
    date: 'June 24, 2026',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '4 min',
    featured: true
  },
  {
    id: 2,
    title: 'Free Fire 9th Anniversary Celebration',
    excerpt: 'Free Fire celebrates its 9th anniversary with the biggest social and in-game event ever.',
    content: 'Garena Free Fire has unleashed its 9th Anniversary with the biggest social and in-game celebration ever. Players can participate in special anniversary events including login rewards, exclusive character skins, and limited-time game modes. The event features a special collaboration with popular creators and in-game giveaways. Don\'t miss the anniversary bundle available in the store for a limited time.',
    category: 'event',
    date: 'June 20, 2026',
    image: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: true
  },
  {
    id: 3,
    title: 'Free Fire x GINTAMA Crossover Announced',
    excerpt: 'Comedy, action, and samurai spirit collide in the limited-time Free Fire x GINTAMA crossover.',
    content: 'Free Fire has announced an exciting new collaboration with the hit anime GINTAMA. This crossover brings unique character bundles, weapon skins, and special in-game events themed around the popular samurai comedy series. Players can collect exclusive GINTAMA-themed items through special events and the premium store. The collaboration will run for a limited time only.',
    category: 'breaking',
    date: 'June 18, 2026',
    image: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: true
  },
  {
    id: 4,
    title: 'FFWS 2026 Esports Roadmap Revealed',
    excerpt: 'Garena unveils expanded global competition with 24 teams in Global Finals.',
    content: 'Garena has revealed the Free Fire 2026 Esports Roadmap with expanded global competition, a new standalone Clash Squad tournament, and EWC return. The Global Finals will feature 24 teams (up from 18) competing for a massive prize pool. The FFWS SEA Spring kicks off April 24 running through May 31, while Fall begins August 14. The Esports World Cup 2026 takes place July 15-18 in Riyadh.',
    category: 'esports',
    date: 'January 19, 2026',
    image: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '5 min',
    featured: true
  },
  {
    id: 5,
    title: 'Jujutsu Kaisen Coming to Free Fire',
    excerpt: 'Awaken the Curse — Jujutsu Kaisen will soon manifest in Free Fire with exclusive content.',
    content: 'Free Fire has confirmed an upcoming collaboration with the massively popular anime Jujutsu Kaisen. Players can expect exclusive character bundles inspired by Yuji Itadori, Gojo Satoru, and other fan-favorite characters. Special cursed energy-themed weapons and effects will also be available. This is shaping up to be one of the biggest anime crossovers in Free Fire history.',
    category: 'breaking',
    date: 'January 15, 2026',
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '4 min',
    featured: true
  },
  {
    id: 6,
    title: 'EVO Vault January 2025 — All New Guns',
    excerpt: 'The Evo Vault has been updated with dazzling new EVO gun skins and rewards.',
    content: 'The Free Fire Evo Vault has been updated with four major EVO weapons: MP40 Chromasonic, Thompson Cindered Colossus, SCAR Megalodon Alpha, and XM8 Destiny Guardian. Each weapon comes with unique upgrade tokens and special effects. The event runs through January 31 on the Indian server. Players can spin the Faded Wheel for a chance to get these premium EVO skins.',
    category: 'evo',
    date: 'January 2, 2025',
    image: 'https://images.unsplash.com/photo-1586287011575-a23134f797f9?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: true
  },
  {
    id: 7,
    title: 'Redeem Codes — July 2026 Active List',
    excerpt: 'Latest active Free Fire redeem codes for July 2026 with rewards and how to claim.',
    content: 'The latest Free Fire MAX redeem codes for July 2026 include P3LX6V9TM2QH, RD3TZK7WME65, ZRW3J4N8VX56, and more. These codes can be redeemed for exclusive in-game rewards including weapon skins, diamonds, and character bundles. Visit the official Free Fire Rewards website to claim your codes before they expire. New codes are released regularly through official social media channels.',
    category: 'update',
    date: 'July 2, 2026',
    image: 'https://images.unsplash.com/photo-1628202926206-c585c53e2c94?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '2 min',
    featured: false
  },
  {
    id: 8,
    title: 'Undersea Mystery — New Ocean Themed Update',
    excerpt: 'Dive into "Undersea Mystery" — Free Fire\'s latest update brings ocean-themed gameplay.',
    content: 'Free Fire has released "Undersea Mystery," a brand new ocean-themed update that introduces underwater combat mechanics, new aquatic weapons, and a special underwater map section. Players can explore sunken ships and discover hidden treasures. The update also brings new character abilities themed around water and ocean powers. New ocean creature pets are also available.',
    category: 'update',
    date: 'March 10, 2026',
    image: 'https://images.unsplash.com/photo-1559827291-baf8a12d7b91?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '4 min',
    featured: false
  },
  {
    id: 9,
    title: 'EWC 2026 — Free Fire Returns to Esports World Cup',
    excerpt: 'Free Fire confirmed for Esports World Cup 2026 in Riyadh with expanded tournament format.',
    content: 'Free Fire has been confirmed as a featured title at the Esports World Cup 2026 in Riyadh, Saudi Arabia from July 15-18. This marks the third consecutive year Free Fire appears at EWC. 24 teams from around the world will compete for a share of the prize pool and the prestigious EWC title. The tournament format will be announced closer to the event date.',
    category: 'esports',
    date: 'January 19, 2026',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: false
  },
  {
    id: 10,
    title: 'Best Sensitivity Settings for 2026',
    excerpt: 'Optimized sensitivity settings for all device tiers — updated for the latest meta.',
    content: 'Finding the perfect sensitivity is crucial for improving your Free Fire gameplay. For premium devices: General 90, Red Dot 85, 2x 75, 4x 60, Sniper 50. For mid-range devices: General 80, Red Dot 75, 2x 65, 4x 50, Sniper 40. Adjust these values based on your personal comfort. Use the ZEUS SENSI tool above to find settings specific to your device model.',
    category: 'guide',
    date: 'June 15, 2026',
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b62f2?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '5 min',
    featured: false
  },
  {
    id: 11,
    title: 'AK47 — Blue Flame Draco Returns',
    excerpt: 'The legendary first EVO gun returns to the store with boosted stats for 2026.',
    content: 'The iconic AK47 Blue Flame Draco has returned to Free Fire with significant stat boosts for 2026. As the original EVO weapon that started the evolutionary skin trend, this dragon-themed AK features damage +25%, fire rate +15%, and new upgraded visual effects. Available in the current Faded Wheel event. Players who already own the skin can upgrade to the new enhanced version.',
    category: 'evo',
    date: 'May 20, 2026',
    image: 'https://images.unsplash.com/photo-1586287011575-a23134f797f9?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: false
  },
  {
    id: 12,
    title: 'Squid Game Crossover in Free Fire',
    excerpt: 'Netflix\'s Squid Game drops into Free Fire in a surprise 8th anniversary crossover event.',
    content: 'Netflix\'s Squid Game is coming to Garena Free Fire in an unexpected crossover event. Players can participate in themed mini-games inspired by the hit series including Red Light Green Light and Dalgona candy challenges. Exclusive Squid Game character bundles, guard uniforms, and themed weapon skins will be available. The crossover also features a special battle pass with Squid Game rewards.',
    category: 'event',
    date: 'August 15, 2025',
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b62f2?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '4 min',
    featured: false
  },
  {
    id: 13,
    title: 'NARUTO SHIPPUDEN Chapter 2 — Ninja War',
    excerpt: 'The battle reignites in Free Fire x NARUTO SHIPPUDEN Chapter 2 with new content.',
    content: 'Free Fire and NARUTO SHIPPUDEN reunite for Chapter 2: Ninja War running July 30 to August 31. New character bundles include Sage Mode Naruto, Sasuke Uchiha (Adult) and more exclusive ninja-themed items. The collaboration features a special Ninja War game mode where players use jutsu abilities. New ninja weapon skins and the Nine Tails Skywing glider are highlights of this event.',
    category: 'event',
    date: 'July 15, 2025',
    image: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: false
  },
  {
    id: 14,
    title: 'Free Fire x Digimon Adventure Collaboration',
    excerpt: 'Calling on courage and evolution — Free Fire kicks off collaboration with Digimon Adventure.',
    content: 'Free Fire has announced a collaboration with the beloved Digimon Adventure franchise starting November 17, 2025. Players can collect Agumon, Gabumon, and other Digimon-themed bundles and accessories. The evolution system is incorporated into special in-game events where players can "digivolve" their gear for enhanced effects. A special Digimon-themed battle pass is also available.',
    category: 'event',
    date: 'November 10, 2025',
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '3 min',
    featured: false
  },
  {
    id: 15,
    title: 'Free Fire Ramadan Cup 2026',
    excerpt: '18 teams compete in Free Fire Ramadan Cup 2026 beginning February 21.',
    content: 'The Free Fire Ramadan Cup 2026 brings together 18 teams from across the region for a special tournament running from February 21. The cup features a unique bracket format and a special Ramadan-themed in-game event alongside the competition. Teams will compete for a prize pool and the prestigious Ramadan Cup trophy. Watch live on the official Free Fire esports channels.',
    category: 'esports',
    date: 'January 19, 2026',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=250&fit=crop',
    author: 'ZEUS',
    readTime: '2 min',
    featured: false
  }
];
